apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kapil.paris.fullname" . }}
  labels:
    {{- include "static-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "static-web.paris.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static-web.paris.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "static-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-paris
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryParis }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-web.fullname" . }}-paris
  labels:
    {{- include "static-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.parisApi.service.type }}
  ports:
   - port: {{ .Values.parisApi.service.port }}
     targetPort: http
     protocol: TCP
     name: http
  selector:
    {{- include "static-web.paris.selectorLabels" . | nindent 4 }}
