apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kapil.virginia.fullname" . }}
  labels:
    {{- include "static-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "static-web.virginia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "static-web.virginia.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "static-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-virginia
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryVirginia }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /usr/local/nginx/conf
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config-volume
        configMap:
           name: nginx-cm
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-web.fullname" . }}-virginia
  labels:
    {{- include "static-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.virginiaApi.service.type }}
  ports:
   - port: {{ .Values.virginiaApi.service.port }}
     targetPort: http
     protocol: TCP
     name: http
  selector:
    {{- include "static-web.virginia.selectorLabels" . | nindent 4 }}
